--user sample
insert into users (username, password, email) values ('Frasco', 'tG4"g$~8uq~&E1d', 'fhammerson0@bbb.org');
insert into users (username, password, email) values ('Archer', 'pL2|hge?', 'afairrie1@simplemachines.org');
insert into users (username, password, email) values ('Tybalt', 'xH5_=aRSVwM2?.', 'tcaser2@seesaa.net');
insert into users (username, password, email) values ('Edgar', 'yY6#v($8LQ=M@rB', 'edimeo3@addtoany.com');
insert into users (username, password, email) values ('Dominick', 'xO6_MOrOr6kZ&AA', 'dfaulconbridge4@jigsy.com');
insert into users (username, password, email) values ('Frederich', 'xI5&cF#buKpg2', 'ffishlock5@nsw.gov.au');
insert into users (username, password, email) values ('Martyn', 'mN3/M''FkTx`#~j', 'mlumsden6@unc.edu');
insert into users (username, password, email) values ('Ingar', 'zA1~5Zx\', 'ibeauly7@php.net');
insert into users (username, password, email) values ('Gaston', 'uF4#%.*!Y', 'gshuter8@reference.com');
insert into users (username, password, email) values ('Bobby', 'rH2`WA26+PN', 'bgruszecki9@dot.gov');
insert into users (username, password, email) values ('Yurik', 'vG5*=9e.''\P*L', 'yrosparsa@ebay.com');
insert into users (username, password, email) values ('Aloin', 'yQ1..Z*}+@i1z', 'ajurnb@amazon.com');
insert into users (username, password, email) values ('Barris', 'zY8*`5OwLMh"w', 'bjeacopc@xinhuanet.com');
insert into users (username, password, email) values ('Mar', 'fN7@t7{2RT', 'mblumired@icq.com');
insert into users (username, password, email) values ('Olenolin', 'qH1@''!e2cEqk', 'oleacocke@constantcontact.com');
insert into users (username, password, email) values ('Delmor', 'qG3"#+._<.zRi{e', 'dfullertonf@quantcast.com');
insert into users (username, password, email) values ('Niels', 'gW1@4{s1Jc*|N!b', 'nspreagg@bloomberg.com');
insert into users (username, password, email) values ('Avery', 'qP4,<_qb', 'akunzlerh@bloomberg.com');
insert into users (username, password, email) values ('Mendel', 'rJ4_WB?9', 'mnutbeani@ustream.tv');
insert into users (username, password, email) values ('Giffy', 'xZ8~3u,P6WIyy~u', 'gratcliffej@chron.com');
insert into users (username, password, email) values ('Jessee', 'aO0!BJ%U', 'jbilbrookek@chron.com');
insert into users (username, password, email) values ('Erie', 'oI2,qjwRUk~4n', 'ebennellickl@tiny.cc');
insert into users (username, password, email) values ('Bern', 'oC0/X)`&', 'blocardm@so-net.ne.jp');
insert into users (username, password, email) values ('Niccolo', 'cH0(A|2{6EpTU=qS', 'nandorn@mediafire.com');
insert into users (username, password, email) values ('Boycey', 'uD6)3eJUOLt_j@g', 'breddingtono@amazonaws.com');
insert into users (username, password, email) values ('Stuart', 'zD1.!rhCW', 'skimbroughp@furl.net');
insert into users (username, password, email) values ('Ken', 'mW2#g5SEB{e', 'kcleevesq@delicious.com');
insert into users (username, password, email) values ('Gary', 'qY8>r><R.K=', 'gcordsenr@stumbleupon.com');
insert into users (username, password, email) values ('Lauritz', 'iF7~Vkt}r''', 'lleideckers@nasa.gov');
insert into users (username, password, email) values ('Ingmar', 'jK1<>|)wOn+(l', 'iwanklynt@ftc.gov');

-- project sample
insert into projects (name, min_duration) values ('Redhold', 19);
insert into projects (name, min_duration) values ('Alpha', 46);
insert into projects (name, min_duration) values ('Bigtax', 23);
insert into projects (name, min_duration) values ('Overhold', 35);
insert into projects (name, min_duration) values ('Transcof', 33);
insert into projects (name, min_duration) values ('Hatity', 16);
insert into projects (name, min_duration) values ('Prodder', 48);
insert into projects (name, min_duration) values ('Trippledex', 28);
insert into projects (name, min_duration) values ('Mat Lam Tam', 31);
insert into projects (name, min_duration) values ('Stronghold', 20);
insert into projects (name, min_duration) values ('Voltsillam', 21);
insert into projects (name, min_duration) values ('Wrapsafe', 15);
insert into projects (name, min_duration) values ('Lotlux', 39);
insert into projects (name, min_duration) values ('Fix San', 45);
insert into projects (name, min_duration) values ('Voltsillam', 46);

--user_project_relation sample
insert into user_project_relation (user_id, project_id) values (4, 9);
insert into user_project_relation (user_id, project_id) values (30, 5);
insert into user_project_relation (user_id, project_id) values (29, 14);
insert into user_project_relation (user_id, project_id) values (23, 8);
insert into user_project_relation (user_id, project_id) values (16, 10);
insert into user_project_relation (user_id, project_id) values (3, 10);
insert into user_project_relation (user_id, project_id) values (30, 7);
insert into user_project_relation (user_id, project_id) values (8, 6);
insert into user_project_relation (user_id, project_id) values (25, 4);
insert into user_project_relation (user_id, project_id) values (4, 10);
insert into user_project_relation (user_id, project_id) values (23, 11);
insert into user_project_relation (user_id, project_id) values (11, 13);
insert into user_project_relation (user_id, project_id) values (21, 8);
insert into user_project_relation (user_id, project_id) values (21, 9);
insert into user_project_relation (user_id, project_id) values (10, 4);
insert into user_project_relation (user_id, project_id) values (6, 11);
insert into user_project_relation (user_id, project_id) values (7, 11);
insert into user_project_relation (user_id, project_id) values (28, 2);
insert into user_project_relation (user_id, project_id) values (17, 12);
insert into user_project_relation (user_id, project_id) values (1, 15);
insert into user_project_relation (user_id, project_id) values (9, 7);
insert into user_project_relation (user_id, project_id) values (27, 5);
insert into user_project_relation (user_id, project_id) values (21, 11);
insert into user_project_relation (user_id, project_id) values (12, 15);
insert into user_project_relation (user_id, project_id) values (27, 14);
insert into user_project_relation (user_id, project_id) values (3, 14);
insert into user_project_relation (user_id, project_id) values (20, 5);
insert into user_project_relation (user_id, project_id) values (9, 3);
insert into user_project_relation (user_id, project_id) values (14, 4);
insert into user_project_relation (user_id, project_id) values (26, 13);


-- messages sample
insert into messages (user_id, project_id, content) values (19, 10, 'in felis donec semper sapien a');
insert into messages (user_id, project_id, content) values (27, 4, 'arcu sed augue aliquam erat volutpat in congue etiam justo');
insert into messages (user_id, project_id, content) values (12, 10, 'leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla');
insert into messages (user_id, project_id, content) values (9, 6, 'consequat in consequat ut nulla sed accumsan felis ut at dolor quis');
insert into messages (user_id, project_id, content) values (21, 11, 'turpis integer aliquet massa id lobortis convallis tortor risus');
insert into messages (user_id, project_id, content) values (30, 9, 'nec condimentum neque sapien placerat');
insert into messages (user_id, project_id, content) values (17, 6, 'imperdiet nullam orci pede venenatis non sodales sed tincidunt eu');
insert into messages (user_id, project_id, content) values (27, 7, 'sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet');
insert into messages (user_id, project_id, content) values (20, 12, 'aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non');
insert into messages (user_id, project_id, content) values (6, 11, 'vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula');
insert into messages (user_id, project_id, content) values (25, 1, 'mattis nibh ligula nec sem duis aliquam convallis');
insert into messages (user_id, project_id, content) values (6, 11, 'at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis');
insert into messages (user_id, project_id, content) values (3, 8, 'nisi vulputate nonummy maecenas tincidunt lacus');
insert into messages (user_id, project_id, content) values (10, 3, 'in tempus sit amet sem fusce consequat nulla nisl nunc nisl');
insert into messages (user_id, project_id, content) values (7, 12, 'primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor');
insert into messages (user_id, project_id, content) values (14, 2, 'nec sem duis aliquam convallis nunc proin at turpis a');
insert into messages (user_id, project_id, content) values (19, 2, 'proin at turpis a pede posuere nonummy integer non velit');
insert into messages (user_id, project_id, content) values (15, 14, 'sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel');
insert into messages (user_id, project_id, content) values (20, 13, 'justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing');
insert into messages (user_id, project_id, content) values (29, 10, 'mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula');
insert into messages (user_id, project_id, content) values (15, 14, 'cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin');
insert into messages (user_id, project_id, content) values (16, 4, 'posuere nonummy integer non velit donec diam neque vestibulum');
insert into messages (user_id, project_id, content) values (30, 8, 'tortor id nulla ultrices aliquet maecenas leo odio');
insert into messages (user_id, project_id, content) values (25, 13, 'convallis duis consequat dui nec nisi');
insert into messages (user_id, project_id, content) values (29, 6, 'odio cras mi pede malesuada in imperdiet et');
insert into messages (user_id, project_id, content) values (24, 4, 'in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices');
insert into messages (user_id, project_id, content) values (21, 4, 'tortor risus dapibus augue vel accumsan tellus');
insert into messages (user_id, project_id, content) values (5, 12, 'purus sit amet nulla quisque arcu');
insert into messages (user_id, project_id, content) values (5, 11, 'ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus');
insert into messages (user_id, project_id, content) values (18, 14, 'in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum');
insert into messages (user_id, project_id, content) values (9, 6, 'in lacus curabitur at ipsum ac');
insert into messages (user_id, project_id, content) values (3, 15, 'ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum');
insert into messages (user_id, project_id, content) values (8, 9, 'fusce consequat nulla nisl nunc');
insert into messages (user_id, project_id, content) values (7, 11, 'phasellus sit amet erat nulla tempus vivamus in felis');
insert into messages (user_id, project_id, content) values (19, 14, 'a odio in hac habitasse platea dictumst maecenas ut massa quis augue');
insert into messages (user_id, project_id, content) values (12, 6, 'sit amet consectetuer adipiscing elit proin');
insert into messages (user_id, project_id, content) values (17, 8, 'vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor');
insert into messages (user_id, project_id, content) values (21, 6, 'sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae');
insert into messages (user_id, project_id, content) values (8, 15, 'porttitor lorem id ligula suspendisse ornare consequat lectus');
insert into messages (user_id, project_id, content) values (2, 6, 'interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et');
insert into messages (user_id, project_id, content) values (10, 5, 'risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum');
insert into messages (user_id, project_id, content) values (23, 7, 'donec dapibus duis at velit eu est congue elementum in hac');
insert into messages (user_id, project_id, content) values (12, 11, 'ultrices posuere cubilia curae mauris viverra diam');
insert into messages (user_id, project_id, content) values (16, 6, 'aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros');
insert into messages (user_id, project_id, content) values (16, 9, 'orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti');
insert into messages (user_id, project_id, content) values (29, 8, 'vel augue vestibulum rutrum rutrum neque');
insert into messages (user_id, project_id, content) values (3, 1, 'sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus');
insert into messages (user_id, project_id, content) values (19, 5, 'nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae');
insert into messages (user_id, project_id, content) values (9, 1, 'morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit');
insert into messages (user_id, project_id, content) values (23, 12, 'ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in');

-- tasks sample
insert into tasks (project_id, name, description) values (3, 'Zamit', 'eu tincidunt in leo maecenas');
insert into tasks (project_id, name, description) values (14, 'Keylex', 'lacinia eget tincidunt eget');
insert into tasks (project_id, name, description) values (13, 'Temp', 'massa quis');
insert into tasks (project_id, name, description) values (15, 'Domainer', 'mus vivamus vestibulum sagittis sapien');
insert into tasks (project_id, name, description) values (4, 'Zaam-Dox', 'magna vestibulum aliquet ultrices');
insert into tasks (project_id, name, description) values (9, 'Alpha', 'duis aliquam');
insert into tasks (project_id, name, description) values (3, 'Bamity', 'nam tristique');
insert into tasks (project_id, name, description) values (13, 'Redhold', 'congue elementum in hac habitasse');
insert into tasks (project_id, name, description) values (8, 'Greenlam', 'ac diam');
insert into tasks (project_id, name, description) values (6, 'Kanlam', 'vestibulum velit id pretium');
insert into tasks (project_id, name, description) values (11, 'Fixflex', 'orci eget orci vehicula');
insert into tasks (project_id, name, description) values (4, 'Fintone', 'varius');
insert into tasks (project_id, name, description) values (9, 'Zontrax', 'vel enim sit');
insert into tasks (project_id, name, description) values (1, 'Stronghold', 'pharetra magna ac');
insert into tasks (project_id, name, description) values (12, 'Biodex', 'etiam vel augue vestibulum rutrum');
insert into tasks (project_id, name, description) values (1, 'Hatity', 'turpis adipiscing');
insert into tasks (project_id, name, description) values (4, 'Mat Lam Tam', 'ante ipsum');
insert into tasks (project_id, name, description) values (5, 'Transcof', 'at dolor quis odio consequat');
insert into tasks (project_id, name, description) values (8, 'Stringtough', 'dis parturient montes');
insert into tasks (project_id, name, description) values (8, 'Tampflex', 'duis bibendum morbi non quam');
insert into tasks (project_id, name, description) values (11, 'Stim', 'a suscipit nulla elit ac');
insert into tasks (project_id, name, description) values (6, 'Redhold', 'sollicitudin mi sit amet');
insert into tasks (project_id, name, description) values (8, 'Alpha', 'dapibus duis at');
insert into tasks (project_id, name, description) values (12, 'Stim', 'lacinia aenean sit');
insert into tasks (project_id, name, description) values (11, 'Tampflex', 'nibh in hac habitasse');
insert into tasks (project_id, name, description) values (1, 'Gembucket', 'primis in faucibus orci luctus');
insert into tasks (project_id, name, description) values (15, 'Voltsillam', 'odio donec');
insert into tasks (project_id, name, description) values (6, 'Lotstring', 'quam sollicitudin vitae consectetuer eget');
insert into tasks (project_id, name, description) values (5, 'Home Ing', 'sit amet sapien dignissim');
insert into tasks (project_id, name, description) values (12, 'Pannier', 'enim blandit mi');
insert into tasks (project_id, name, description) values (3, 'Aerified', 'eget orci vehicula');
insert into tasks (project_id, name, description) values (2, 'Konklab', 'aliquam non mauris');
insert into tasks (project_id, name, description) values (14, 'Gembucket', 'auctor gravida sem');
insert into tasks (project_id, name, description) values (15, 'Biodex', 'mollis molestie lorem quisque ut');
insert into tasks (project_id, name, description) values (9, 'Gembucket', 'nec nisi');
insert into tasks (project_id, name, description) values (3, 'Sonair', 'metus aenean fermentum');
insert into tasks (project_id, name, description) values (15, 'Temp', 'duis mattis egestas metus aenean');
insert into tasks (project_id, name, description) values (6, 'Cookley', 'ipsum dolor');
insert into tasks (project_id, name, description) values (2, 'Temp', 'volutpat dui');
insert into tasks (project_id, name, description) values (14, 'Aerified', 'id sapien in');
insert into tasks (project_id, name, description) values (12, 'Otcom', 'ultrices');
insert into tasks (project_id, name, description) values (7, 'Alpha', 'eu magna vulputate');
insert into tasks (project_id, name, description) values (9, 'Cookley', 'proin eu mi nulla ac');
insert into tasks (project_id, name, description) values (4, 'Flexidy', 'duis mattis egestas');

-- user_task_relation
insert into user_task_relation (task_id, user_project_relation_id) values (17, 11);
insert into user_task_relation (task_id, user_project_relation_id) values (19, 8);
insert into user_task_relation (task_id, user_project_relation_id) values (21, 5);
insert into user_task_relation (task_id, user_project_relation_id) values (41, 22);
insert into user_task_relation (task_id, user_project_relation_id) values (47, 29);
insert into user_task_relation (task_id, user_project_relation_id) values (44, 8);
insert into user_task_relation (task_id, user_project_relation_id) values (4, 27);
insert into user_task_relation (task_id, user_project_relation_id) values (17, 25);
insert into user_task_relation (task_id, user_project_relation_id) values (21, 29);
insert into user_task_relation (task_id, user_project_relation_id) values (37, 19);
insert into user_task_relation (task_id, user_project_relation_id) values (41, 10);
insert into user_task_relation (task_id, user_project_relation_id) values (50, 30);
insert into user_task_relation (task_id, user_project_relation_id) values (4, 17);
insert into user_task_relation (task_id, user_project_relation_id) values (13, 29);
insert into user_task_relation (task_id, user_project_relation_id) values (32, 20);
insert into user_task_relation (task_id, user_project_relation_id) values (37, 7);
insert into user_task_relation (task_id, user_project_relation_id) values (41, 12);
insert into user_task_relation (task_id, user_project_relation_id) values (4, 23);
insert into user_task_relation (task_id, user_project_relation_id) values (49, 1);
insert into user_task_relation (task_id, user_project_relation_id) values (25, 30);
insert into user_task_relation (task_id, user_project_relation_id) values (4, 11);
insert into user_task_relation (task_id, user_project_relation_id) values (30, 10);
insert into user_task_relation (task_id, user_project_relation_id) values (25, 12);
insert into user_task_relation (task_id, user_project_relation_id) values (27, 16);
insert into user_task_relation (task_id, user_project_relation_id) values (45, 10);
insert into user_task_relation (task_id, user_project_relation_id) values (31, 15);
insert into user_task_relation (task_id, user_project_relation_id) values (15, 11);
insert into user_task_relation (task_id, user_project_relation_id) values (11, 20);
insert into user_task_relation (task_id, user_project_relation_id) values (47, 10);
insert into user_task_relation (task_id, user_project_relation_id) values (13, 3);
insert into user_task_relation (task_id, user_project_relation_id) values (20, 7);
insert into user_task_relation (task_id, user_project_relation_id) values (23, 28);
insert into user_task_relation (task_id, user_project_relation_id) values (4, 23);
insert into user_task_relation (task_id, user_project_relation_id) values (21, 29);
insert into user_task_relation (task_id, user_project_relation_id) values (8, 29);
insert into user_task_relation (task_id, user_project_relation_id) values (34, 23);
insert into user_task_relation (task_id, user_project_relation_id) values (39, 6);
insert into user_task_relation (task_id, user_project_relation_id) values (17, 29);
insert into user_task_relation (task_id, user_project_relation_id) values (25, 7);
insert into user_task_relation (task_id, user_project_relation_id) values (23, 21);
insert into user_task_relation (task_id, user_project_relation_id) values (20, 27);
insert into user_task_relation (task_id, user_project_relation_id) values (34, 7);
insert into user_task_relation (task_id, user_project_relation_id) values (16, 7);
insert into user_task_relation (task_id, user_project_relation_id) values (18, 15);
insert into user_task_relation (task_id, user_project_relation_id) values (5, 19);
insert into user_task_relation (task_id, user_project_relation_id) values (34, 24);
insert into user_task_relation (task_id, user_project_relation_id) values (40, 29);
insert into user_task_relation (task_id, user_project_relation_id) values (27, 28);
insert into user_task_relation (task_id, user_project_relation_id) values (45, 28);
insert into user_task_relation (task_id, user_project_relation_id) values (12, 8);



--test project
insert into users (username, password, email) values ('Frasco', 'tG4"g$~8uq~&E1d', 'fhammerson0@bbb.org');
insert into projects (name, start_date,min_duration) values ('Alpha', '2024-04-01',25);
insert into user_project_relation (user_id, project_id) values (1, 1);


--project 10 taskname ,startdate , duration, dependencies
insert into tasks (project_id, name, duration, start_date) values (1, 'root Project', 0,'2024-04-01');
insert into tasks (project_id, name, duration, start_date) values (1, 'Sonair', 4,'2024-04-01');
insert into tasks (project_id, name, duration, start_date) values (1, 'Tres-Zap', 3,'2024-04-05');
insert into tasks (project_id, name, duration, start_date) values (1, 'Tin', 6,'2024-04-05');
insert into tasks (project_id, name, duration, start_date) values (1, 'Alpha', 4,'2024-04-11');
insert into tasks (project_id, name, duration, start_date) values (1, 'Bytecard', 1,'2024-04-08');
insert into tasks (project_id, name, duration, start_date) values (1, 'Regrant', 8,'2024-04-08');
insert into tasks (project_id, name, duration, start_date) values (1, 'Hatity', 3,'2024-04-08');
insert into tasks (project_id, name, duration, start_date) values (1, 'Mat Lam Tam', 6,'2024-04-11');
insert into tasks (project_id, name, duration, start_date) values (1, 'Transcof', 9,'2024-04-09');
insert into tasks (project_id, name, duration, start_date) values (1, 'Stringtough', 2,'2024-04-15');
insert into tasks (project_id, name, duration, start_date) values (1, 'Tampflex', 8,'2024-04-16');

-- project 10 task relation
insert into task_relation (task_id, pre_req_task_id) values (2, 1);
insert into task_relation (task_id, pre_req_task_id) values (3, 2);
insert into task_relation (task_id, pre_req_task_id) values (4, 2);
insert into task_relation (task_id, pre_req_task_id) values (5, 4);
insert into task_relation (task_id, pre_req_task_id) values (6, 3);
insert into task_relation (task_id, pre_req_task_id) values (7, 3);
insert into task_relation (task_id, pre_req_task_id) values (8, 3);
insert into task_relation (task_id, pre_req_task_id) values (9, 8);
insert into task_relation (task_id, pre_req_task_id) values (10, 6);
insert into task_relation (task_id, pre_req_task_id) values (11, 5);
insert into task_relation (task_id, pre_req_task_id) values (12, 10);
insert into task_relation (task_id, pre_req_task_id) values (12, 7);